### PR TITLE
thanks!

### PR DESCRIPTION
**Pull request by timo1160139211**

### CODE REVIEW

**Comment by amaruk** [comment]
Please do not change the feature branch.
We accept pull request for "gh-pages" only.
Thank you.

**Comment by timo1160139211** [comment]
Thanks for reply.
I am sorry about that.
I'll try again latter.
:-)

**Comment by timo1160139211** [comment]
Sorry , and  I am not sure why GitHub (in this PR) shows ' timo1160139211  wants to merge 1,635 commits '.
Are they differences of two branches?
Looking forward to your reply.
Thanks.

**Comment by amaruk** [comment]
The **gh-pages** branch is used for pull request testing, while **feature/move-jquery-from-cdn-to-local** was created for feature development 2 years ago.

Did you **clone** and modify this repository directly?
Try to **fork** this repository first. Clone the forked repository and modify your local **gh-pages** branch. Then commit and push to your own repository, and create a new pull request. Good luck.

**Comment by timo1160139211** [comment]
Thanks a lot. I'll try again latter. 
; - )

**Pull request closed without merging**
